#ifndef IRIS_PREPROCESS_FOR_HPP
#define IRIS_PREPROCESS_FOR_HPP

#include <iris/preprocess/if.hpp>

#define IRIS_PP_FOR(state, pred, update, macro) IRIS_PP_FOR_I_0(state, pred, update, macro)

#define IRIS_PP_FOR_I_0(state, pred, op, macro) IRIS_PP_FOR_I_I_0(state, pred, op, macro)
#define IRIS_PP_FOR_I_1(state, pred, op, macro) IRIS_PP_FOR_I_I_1(state, pred, op, macro)
#define IRIS_PP_FOR_I_2(state, pred, op, macro) IRIS_PP_FOR_I_I_2(state, pred, op, macro)
#define IRIS_PP_FOR_I_3(state, pred, op, macro) IRIS_PP_FOR_I_I_3(state, pred, op, macro)
#define IRIS_PP_FOR_I_4(state, pred, op, macro) IRIS_PP_FOR_I_I_4(state, pred, op, macro)
#define IRIS_PP_FOR_I_5(state, pred, op, macro) IRIS_PP_FOR_I_I_5(state, pred, op, macro)
#define IRIS_PP_FOR_I_6(state, pred, op, macro) IRIS_PP_FOR_I_I_6(state, pred, op, macro)
#define IRIS_PP_FOR_I_7(state, pred, op, macro) IRIS_PP_FOR_I_I_7(state, pred, op, macro)
#define IRIS_PP_FOR_I_8(state, pred, op, macro) IRIS_PP_FOR_I_I_8(state, pred, op, macro)
#define IRIS_PP_FOR_I_9(state, pred, op, macro) IRIS_PP_FOR_I_I_9(state, pred, op, macro)
#define IRIS_PP_FOR_I_10(state, pred, op, macro) IRIS_PP_FOR_I_I_10(state, pred, op, macro)
#define IRIS_PP_FOR_I_11(state, pred, op, macro) IRIS_PP_FOR_I_I_11(state, pred, op, macro)
#define IRIS_PP_FOR_I_12(state, pred, op, macro) IRIS_PP_FOR_I_I_12(state, pred, op, macro)
#define IRIS_PP_FOR_I_13(state, pred, op, macro) IRIS_PP_FOR_I_I_13(state, pred, op, macro)
#define IRIS_PP_FOR_I_14(state, pred, op, macro) IRIS_PP_FOR_I_I_14(state, pred, op, macro)
#define IRIS_PP_FOR_I_15(state, pred, op, macro) IRIS_PP_FOR_I_I_15(state, pred, op, macro)
#define IRIS_PP_FOR_I_16(state, pred, op, macro) IRIS_PP_FOR_I_I_16(state, pred, op, macro)
#define IRIS_PP_FOR_I_17(state, pred, op, macro) IRIS_PP_FOR_I_I_17(state, pred, op, macro)
#define IRIS_PP_FOR_I_18(state, pred, op, macro) IRIS_PP_FOR_I_I_18(state, pred, op, macro)
#define IRIS_PP_FOR_I_19(state, pred, op, macro) IRIS_PP_FOR_I_I_19(state, pred, op, macro)
#define IRIS_PP_FOR_I_20(state, pred, op, macro) IRIS_PP_FOR_I_I_20(state, pred, op, macro)
#define IRIS_PP_FOR_I_21(state, pred, op, macro) IRIS_PP_FOR_I_I_21(state, pred, op, macro)
#define IRIS_PP_FOR_I_22(state, pred, op, macro) IRIS_PP_FOR_I_I_22(state, pred, op, macro)
#define IRIS_PP_FOR_I_23(state, pred, op, macro) IRIS_PP_FOR_I_I_23(state, pred, op, macro)
#define IRIS_PP_FOR_I_24(state, pred, op, macro) IRIS_PP_FOR_I_I_24(state, pred, op, macro)
#define IRIS_PP_FOR_I_25(state, pred, op, macro) IRIS_PP_FOR_I_I_25(state, pred, op, macro)
#define IRIS_PP_FOR_I_26(state, pred, op, macro) IRIS_PP_FOR_I_I_26(state, pred, op, macro)
#define IRIS_PP_FOR_I_27(state, pred, op, macro) IRIS_PP_FOR_I_I_27(state, pred, op, macro)
#define IRIS_PP_FOR_I_28(state, pred, op, macro) IRIS_PP_FOR_I_I_28(state, pred, op, macro)
#define IRIS_PP_FOR_I_29(state, pred, op, macro) IRIS_PP_FOR_I_I_29(state, pred, op, macro)
#define IRIS_PP_FOR_I_30(state, pred, op, macro) IRIS_PP_FOR_I_I_30(state, pred, op, macro)
#define IRIS_PP_FOR_I_31(state, pred, op, macro) IRIS_PP_FOR_I_I_31(state, pred, op, macro)

#define IRIS_PP_FOR_I_I_0(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_1(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_1(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_2(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_2(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_3(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_3(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_4(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_4(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_5(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_5(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_6(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_6(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_7(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_7(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_8(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_8(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_9(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_9(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_10(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_10(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_11(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_11(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_12(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_12(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_13(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_13(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_14(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_14(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_15(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_15(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_16(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_16(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_17(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_17(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_18(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_18(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_19(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_19(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_20(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_20(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_21(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_21(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_22(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_22(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_23(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_23(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_24(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_24(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_25(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_25(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_26(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_26(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_27(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_27(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_28(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_28(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_29(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_29(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_30(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_30(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_31(op(state), pred, op, macro), )
#define IRIS_PP_FOR_I_I_31(state, pred, op, macro) IRIS_PP_IF(pred(state), macro(state) IRIS_PP_FOR_I_32(op(state), pred, op, macro), )

#endif
