#ifndef IRIS_ZZ_PREPROCESS_ADD_HPP
#define IRIS_ZZ_PREPROCESS_ADD_HPP

// SPDX-License-Identifier: MIT

#include <iris/pp/cat.hpp>
#include <iris/pp/increment.hpp>

#define IRIS_PP_ADD(a, b) IRIS_PP_CAT(IRIS_ZZ_PP_ADD_I_, b)(a)

#define IRIS_ZZ_PP_ADD_I_0(a) a
#define IRIS_ZZ_PP_ADD_I_1(a) IRIS_ZZ_PP_ADD_I_0(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_2(a) IRIS_ZZ_PP_ADD_I_1(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_3(a) IRIS_ZZ_PP_ADD_I_2(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_4(a) IRIS_ZZ_PP_ADD_I_3(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_5(a) IRIS_ZZ_PP_ADD_I_4(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_6(a) IRIS_ZZ_PP_ADD_I_5(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_7(a) IRIS_ZZ_PP_ADD_I_6(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_8(a) IRIS_ZZ_PP_ADD_I_7(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_9(a) IRIS_ZZ_PP_ADD_I_8(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_10(a) IRIS_ZZ_PP_ADD_I_9(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_11(a) IRIS_ZZ_PP_ADD_I_10(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_12(a) IRIS_ZZ_PP_ADD_I_11(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_13(a) IRIS_ZZ_PP_ADD_I_12(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_14(a) IRIS_ZZ_PP_ADD_I_13(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_15(a) IRIS_ZZ_PP_ADD_I_14(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_16(a) IRIS_ZZ_PP_ADD_I_15(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_17(a) IRIS_ZZ_PP_ADD_I_16(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_18(a) IRIS_ZZ_PP_ADD_I_17(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_19(a) IRIS_ZZ_PP_ADD_I_18(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_20(a) IRIS_ZZ_PP_ADD_I_19(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_21(a) IRIS_ZZ_PP_ADD_I_20(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_22(a) IRIS_ZZ_PP_ADD_I_21(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_23(a) IRIS_ZZ_PP_ADD_I_22(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_24(a) IRIS_ZZ_PP_ADD_I_23(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_25(a) IRIS_ZZ_PP_ADD_I_24(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_26(a) IRIS_ZZ_PP_ADD_I_25(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_27(a) IRIS_ZZ_PP_ADD_I_26(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_28(a) IRIS_ZZ_PP_ADD_I_27(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_29(a) IRIS_ZZ_PP_ADD_I_28(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_30(a) IRIS_ZZ_PP_ADD_I_29(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_31(a) IRIS_ZZ_PP_ADD_I_30(IRIS_PP_INCREMENT(a))
#define IRIS_ZZ_PP_ADD_I_32(a) IRIS_ZZ_PP_ADD_I_31(IRIS_PP_INCREMENT(a))

#endif
