#ifndef IRIS_ZZ_PP_ARG_HPP
#define IRIS_ZZ_PP_ARG_HPP

// SPDX-License-Identifier: MIT

#define IRIS_PP_IDENTITY(...) __VA_ARGS__

#define IRIS_PP_EMPTY(...)

#define IRIS_ZZ_PP_EXPAND_I(...) __VA_ARGS__
#define IRIS_PP_EXPAND(...) IRIS_ZZ_PP_EXPAND_I(__VA_ARGS__)

#define IRIS_ZZ_PP_PAREN_PROBE() ~, 1

#define IRIS_ZZ_PP_SECOND(a, b, ...) b
#define IRIS_ZZ_PP_PAREN_PROBE_CHECK(...) IRIS_ZZ_PP_SECOND(__VA_ARGS__, 0)
#define IRIS_ZZ_PP_IS_PAREN_PROBE(...) IRIS_ZZ_PP_PAREN_PROBE()

#define IRIS_PP_IS_PAREN(x) IRIS_ZZ_PP_PAREN_PROBE_CHECK(IRIS_ZZ_PP_IS_PAREN_PROBE x)

#define IRIS_PP_UNPAREN(x) IRIS_PP_EXPAND x

#define IRIS_ZZ_PP_UNPAREN_ESC(...) IRIS_ZZ_PP_UNPAREN_ESC __VA_ARGS__
#define IRIS_ZZ_PP_UNPAREN_VANISH_IRIS_ZZ_PP_UNPAREN_ESC
#define IRIS_ZZ_PP_UNPAREN_IF_PAREN_II(...) IRIS_ZZ_PP_UNPAREN_VANISH_ ## __VA_ARGS__
#define IRIS_ZZ_PP_UNPAREN_IF_PAREN_I(...) IRIS_ZZ_PP_UNPAREN_IF_PAREN_II(__VA_ARGS__)
#define IRIS_PP_UNPAREN_IF_PAREN(x) IRIS_ZZ_PP_UNPAREN_IF_PAREN_I(IRIS_ZZ_PP_UNPAREN_ESC x)

#endif
