#ifndef IRIS_PREPROCESS_DECREMENT_HPP
#define IRIS_PREPROCESS_DECREMENT_HPP

// SPDX-License-Identifier: MIT

#include <iris/pp/cat.hpp>

#define IRIS_PP_DECREMENT(expr) IRIS_PP_CAT(IRIS_PP_DECREMENT_I_, expr)

#define IRIS_PP_DECREMENT_I_1 0
#define IRIS_PP_DECREMENT_I_2 1
#define IRIS_PP_DECREMENT_I_3 2
#define IRIS_PP_DECREMENT_I_4 3
#define IRIS_PP_DECREMENT_I_5 4
#define IRIS_PP_DECREMENT_I_6 5
#define IRIS_PP_DECREMENT_I_7 6
#define IRIS_PP_DECREMENT_I_8 7
#define IRIS_PP_DECREMENT_I_9 8
#define IRIS_PP_DECREMENT_I_10 9
#define IRIS_PP_DECREMENT_I_11 10
#define IRIS_PP_DECREMENT_I_12 11
#define IRIS_PP_DECREMENT_I_13 12
#define IRIS_PP_DECREMENT_I_14 13
#define IRIS_PP_DECREMENT_I_15 14
#define IRIS_PP_DECREMENT_I_16 15
#define IRIS_PP_DECREMENT_I_17 16
#define IRIS_PP_DECREMENT_I_18 17
#define IRIS_PP_DECREMENT_I_19 18
#define IRIS_PP_DECREMENT_I_20 19
#define IRIS_PP_DECREMENT_I_21 20
#define IRIS_PP_DECREMENT_I_22 21
#define IRIS_PP_DECREMENT_I_23 22
#define IRIS_PP_DECREMENT_I_24 23
#define IRIS_PP_DECREMENT_I_25 24
#define IRIS_PP_DECREMENT_I_26 25
#define IRIS_PP_DECREMENT_I_27 26
#define IRIS_PP_DECREMENT_I_28 27
#define IRIS_PP_DECREMENT_I_29 28
#define IRIS_PP_DECREMENT_I_30 29
#define IRIS_PP_DECREMENT_I_31 30
#define IRIS_PP_DECREMENT_I_32 31

#endif
