#ifndef IRIS_PREPROCESS_INCREMENT_HPP
#define IRIS_PREPROCESS_INCREMENT_HPP

#include <iris/pp/cat.hpp>

#define IRIS_PP_INCREMENT(expr) IRIS_PP_CAT(IRIS_PP_INCREMENT_I_, expr)

#define IRIS_PP_INCREMENT_I_0 1
#define IRIS_PP_INCREMENT_I_1 2
#define IRIS_PP_INCREMENT_I_2 3
#define IRIS_PP_INCREMENT_I_3 4
#define IRIS_PP_INCREMENT_I_4 5
#define IRIS_PP_INCREMENT_I_5 6
#define IRIS_PP_INCREMENT_I_6 7
#define IRIS_PP_INCREMENT_I_7 8
#define IRIS_PP_INCREMENT_I_8 9
#define IRIS_PP_INCREMENT_I_9 10
#define IRIS_PP_INCREMENT_I_10 11
#define IRIS_PP_INCREMENT_I_11 12
#define IRIS_PP_INCREMENT_I_12 13
#define IRIS_PP_INCREMENT_I_13 14
#define IRIS_PP_INCREMENT_I_14 15
#define IRIS_PP_INCREMENT_I_15 16
#define IRIS_PP_INCREMENT_I_16 17
#define IRIS_PP_INCREMENT_I_17 18
#define IRIS_PP_INCREMENT_I_18 19
#define IRIS_PP_INCREMENT_I_19 20
#define IRIS_PP_INCREMENT_I_20 21
#define IRIS_PP_INCREMENT_I_21 22
#define IRIS_PP_INCREMENT_I_22 23
#define IRIS_PP_INCREMENT_I_23 24
#define IRIS_PP_INCREMENT_I_24 25
#define IRIS_PP_INCREMENT_I_25 26
#define IRIS_PP_INCREMENT_I_26 27
#define IRIS_PP_INCREMENT_I_27 28
#define IRIS_PP_INCREMENT_I_28 29
#define IRIS_PP_INCREMENT_I_29 30
#define IRIS_PP_INCREMENT_I_30 31
#define IRIS_PP_INCREMENT_I_31 32

#endif
