#ifndef IRIS_PREPROCESS_REPEAT_HPP
#define IRIS_PREPROCESS_REPEAT_HPP

// SPDX-License-Identifier: MIT

#include <iris/pp/add.hpp>
#include <iris/pp/cat.hpp>
#include <iris/pp/rec.hpp>
#include <iris/pp/sub.hpp>

#define IRIS_PP_REPEAT IRIS_PP_CAT(IRIS_PP_REPEAT_, IRIS_PP_REC(IRIS_PP_REPEAT_I_PRED, 8))

#define IRIS_PP_REPEAT_I_EAT_2(a, b)
#define IRIS_PP_REPEAT_I_PRED(n) \
    IRIS_PP_CAT(IRIS_PP_REPEAT_I_CHECK_, IRIS_PP_CAT(IRIS_PP_REPEAT_, n)(1, IRIS_PP_REPEAT_I_NIL IRIS_PP_REPEAT_I_EAT_2, IRIS_PP_REPEAT_I_NIL))

#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_I_NIL 1
#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_1(count, macro, data) 0
#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_2(count, macro, data) 0
#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_3(count, macro, data) 0
#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_4(count, macro, data) 0
#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_5(count, macro, data) 0
#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_6(count, macro, data) 0
#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_7(count, macro, data) 0
#define IRIS_PP_REPEAT_I_CHECK_IRIS_PP_REPEAT_8(count, macro, data) 0

#define IRIS_PP_REPEAT_1(count, macro, data) IRIS_PP_CAT(IRIS_PP_REPEAT_1_I_, count)(macro, data)
#define IRIS_PP_REPEAT_2(count, macro, data) IRIS_PP_CAT(IRIS_PP_REPEAT_2_I_, count)(macro, data)
#define IRIS_PP_REPEAT_3(count, macro, data) IRIS_PP_CAT(IRIS_PP_REPEAT_3_I_, count)(macro, data)
#define IRIS_PP_REPEAT_4(count, macro, data) IRIS_PP_CAT(IRIS_PP_REPEAT_4_I_, count)(macro, data)
#define IRIS_PP_REPEAT_5(count, macro, data) IRIS_PP_CAT(IRIS_PP_REPEAT_5_I_, count)(macro, data)
#define IRIS_PP_REPEAT_6(count, macro, data) IRIS_PP_CAT(IRIS_PP_REPEAT_6_I_, count)(macro, data)
#define IRIS_PP_REPEAT_7(count, macro, data) IRIS_PP_CAT(IRIS_PP_REPEAT_7_I_, count)(macro, data)
#define IRIS_PP_REPEAT_8(count, macro, data) IRIS_PP_CAT(IRIS_PP_REPEAT_8_I_, count)(macro, data)

#define IRIS_PP_REPEAT_FROM_TO(from, to, macro, data) IRIS_PP_REPEAT(IRIS_PP_SUB(to, from), IRIS_PP_REPEAT_FROM_TO_I, (macro, from, data))

#define IRIS_PP_REPEAT_FROM_TO_I_MACRO(state) IRIS_PP_REPEAT_FROM_TO_I_MACRO_I state
#define IRIS_PP_REPEAT_FROM_TO_I_MACRO_I(macro, from, data) macro

#define IRIS_PP_REPEAT_FROM_TO_I_FROM(state) IRIS_PP_REPEAT_FROM_TO_I_FROM_I state
#define IRIS_PP_REPEAT_FROM_TO_I_FROM_I(macro, from, data) from

#define IRIS_PP_REPEAT_FROM_TO_I_DATA(state) IRIS_PP_REPEAT_FROM_TO_I_DATA_I state
#define IRIS_PP_REPEAT_FROM_TO_I_DATA_I(macro, from, data) data

#define IRIS_PP_REPEAT_FROM_TO_I(index, state) \
    IRIS_PP_REPEAT_FROM_TO_I_MACRO(state)(IRIS_PP_ADD(index, IRIS_PP_REPEAT_FROM_TO_I_FROM(state)), IRIS_PP_REPEAT_FROM_TO_I_DATA(state))

#define IRIS_PP_REPEAT_1_I_0(macro, data)
#define IRIS_PP_REPEAT_1_I_1(macro, data) macro(0, data)
#define IRIS_PP_REPEAT_1_I_2(macro, data) IRIS_PP_REPEAT_1_I_1(macro, data) macro(1, data)
#define IRIS_PP_REPEAT_1_I_3(macro, data) IRIS_PP_REPEAT_1_I_2(macro, data) macro(2, data)
#define IRIS_PP_REPEAT_1_I_4(macro, data) IRIS_PP_REPEAT_1_I_3(macro, data) macro(3, data)
#define IRIS_PP_REPEAT_1_I_5(macro, data) IRIS_PP_REPEAT_1_I_4(macro, data) macro(4, data)
#define IRIS_PP_REPEAT_1_I_6(macro, data) IRIS_PP_REPEAT_1_I_5(macro, data) macro(5, data)
#define IRIS_PP_REPEAT_1_I_7(macro, data) IRIS_PP_REPEAT_1_I_6(macro, data) macro(6, data)
#define IRIS_PP_REPEAT_1_I_8(macro, data) IRIS_PP_REPEAT_1_I_7(macro, data) macro(7, data)
#define IRIS_PP_REPEAT_1_I_9(macro, data) IRIS_PP_REPEAT_1_I_8(macro, data) macro(8, data)
#define IRIS_PP_REPEAT_1_I_10(macro, data) IRIS_PP_REPEAT_1_I_9(macro, data) macro(9, data)
#define IRIS_PP_REPEAT_1_I_11(macro, data) IRIS_PP_REPEAT_1_I_10(macro, data) macro(10, data)
#define IRIS_PP_REPEAT_1_I_12(macro, data) IRIS_PP_REPEAT_1_I_11(macro, data) macro(11, data)
#define IRIS_PP_REPEAT_1_I_13(macro, data) IRIS_PP_REPEAT_1_I_12(macro, data) macro(12, data)
#define IRIS_PP_REPEAT_1_I_14(macro, data) IRIS_PP_REPEAT_1_I_13(macro, data) macro(13, data)
#define IRIS_PP_REPEAT_1_I_15(macro, data) IRIS_PP_REPEAT_1_I_14(macro, data) macro(14, data)
#define IRIS_PP_REPEAT_1_I_16(macro, data) IRIS_PP_REPEAT_1_I_15(macro, data) macro(15, data)
#define IRIS_PP_REPEAT_1_I_17(macro, data) IRIS_PP_REPEAT_1_I_16(macro, data) macro(16, data)
#define IRIS_PP_REPEAT_1_I_18(macro, data) IRIS_PP_REPEAT_1_I_17(macro, data) macro(17, data)
#define IRIS_PP_REPEAT_1_I_19(macro, data) IRIS_PP_REPEAT_1_I_18(macro, data) macro(18, data)
#define IRIS_PP_REPEAT_1_I_20(macro, data) IRIS_PP_REPEAT_1_I_19(macro, data) macro(19, data)
#define IRIS_PP_REPEAT_1_I_21(macro, data) IRIS_PP_REPEAT_1_I_20(macro, data) macro(20, data)
#define IRIS_PP_REPEAT_1_I_22(macro, data) IRIS_PP_REPEAT_1_I_21(macro, data) macro(21, data)
#define IRIS_PP_REPEAT_1_I_23(macro, data) IRIS_PP_REPEAT_1_I_22(macro, data) macro(22, data)
#define IRIS_PP_REPEAT_1_I_24(macro, data) IRIS_PP_REPEAT_1_I_23(macro, data) macro(23, data)
#define IRIS_PP_REPEAT_1_I_25(macro, data) IRIS_PP_REPEAT_1_I_24(macro, data) macro(24, data)
#define IRIS_PP_REPEAT_1_I_26(macro, data) IRIS_PP_REPEAT_1_I_25(macro, data) macro(25, data)
#define IRIS_PP_REPEAT_1_I_27(macro, data) IRIS_PP_REPEAT_1_I_26(macro, data) macro(26, data)
#define IRIS_PP_REPEAT_1_I_28(macro, data) IRIS_PP_REPEAT_1_I_27(macro, data) macro(27, data)
#define IRIS_PP_REPEAT_1_I_29(macro, data) IRIS_PP_REPEAT_1_I_28(macro, data) macro(28, data)
#define IRIS_PP_REPEAT_1_I_30(macro, data) IRIS_PP_REPEAT_1_I_29(macro, data) macro(29, data)
#define IRIS_PP_REPEAT_1_I_31(macro, data) IRIS_PP_REPEAT_1_I_30(macro, data) macro(30, data)
#define IRIS_PP_REPEAT_1_I_32(macro, data) IRIS_PP_REPEAT_1_I_31(macro, data) macro(31, data)

#define IRIS_PP_REPEAT_2_I_0(macro, data)
#define IRIS_PP_REPEAT_2_I_1(macro, data) macro(0, data)
#define IRIS_PP_REPEAT_2_I_2(macro, data) IRIS_PP_REPEAT_2_I_1(macro, data) macro(1, data)
#define IRIS_PP_REPEAT_2_I_3(macro, data) IRIS_PP_REPEAT_2_I_2(macro, data) macro(2, data)
#define IRIS_PP_REPEAT_2_I_4(macro, data) IRIS_PP_REPEAT_2_I_3(macro, data) macro(3, data)
#define IRIS_PP_REPEAT_2_I_5(macro, data) IRIS_PP_REPEAT_2_I_4(macro, data) macro(4, data)
#define IRIS_PP_REPEAT_2_I_6(macro, data) IRIS_PP_REPEAT_2_I_5(macro, data) macro(5, data)
#define IRIS_PP_REPEAT_2_I_7(macro, data) IRIS_PP_REPEAT_2_I_6(macro, data) macro(6, data)
#define IRIS_PP_REPEAT_2_I_8(macro, data) IRIS_PP_REPEAT_2_I_7(macro, data) macro(7, data)
#define IRIS_PP_REPEAT_2_I_9(macro, data) IRIS_PP_REPEAT_2_I_8(macro, data) macro(8, data)
#define IRIS_PP_REPEAT_2_I_10(macro, data) IRIS_PP_REPEAT_2_I_9(macro, data) macro(9, data)
#define IRIS_PP_REPEAT_2_I_11(macro, data) IRIS_PP_REPEAT_2_I_10(macro, data) macro(10, data)
#define IRIS_PP_REPEAT_2_I_12(macro, data) IRIS_PP_REPEAT_2_I_11(macro, data) macro(11, data)
#define IRIS_PP_REPEAT_2_I_13(macro, data) IRIS_PP_REPEAT_2_I_12(macro, data) macro(12, data)
#define IRIS_PP_REPEAT_2_I_14(macro, data) IRIS_PP_REPEAT_2_I_13(macro, data) macro(13, data)
#define IRIS_PP_REPEAT_2_I_15(macro, data) IRIS_PP_REPEAT_2_I_14(macro, data) macro(14, data)
#define IRIS_PP_REPEAT_2_I_16(macro, data) IRIS_PP_REPEAT_2_I_15(macro, data) macro(15, data)
#define IRIS_PP_REPEAT_2_I_17(macro, data) IRIS_PP_REPEAT_2_I_16(macro, data) macro(16, data)
#define IRIS_PP_REPEAT_2_I_18(macro, data) IRIS_PP_REPEAT_2_I_17(macro, data) macro(17, data)
#define IRIS_PP_REPEAT_2_I_19(macro, data) IRIS_PP_REPEAT_2_I_18(macro, data) macro(18, data)
#define IRIS_PP_REPEAT_2_I_20(macro, data) IRIS_PP_REPEAT_2_I_19(macro, data) macro(19, data)
#define IRIS_PP_REPEAT_2_I_21(macro, data) IRIS_PP_REPEAT_2_I_20(macro, data) macro(20, data)
#define IRIS_PP_REPEAT_2_I_22(macro, data) IRIS_PP_REPEAT_2_I_21(macro, data) macro(21, data)
#define IRIS_PP_REPEAT_2_I_23(macro, data) IRIS_PP_REPEAT_2_I_22(macro, data) macro(22, data)
#define IRIS_PP_REPEAT_2_I_24(macro, data) IRIS_PP_REPEAT_2_I_23(macro, data) macro(23, data)
#define IRIS_PP_REPEAT_2_I_25(macro, data) IRIS_PP_REPEAT_2_I_24(macro, data) macro(24, data)
#define IRIS_PP_REPEAT_2_I_26(macro, data) IRIS_PP_REPEAT_2_I_25(macro, data) macro(25, data)
#define IRIS_PP_REPEAT_2_I_27(macro, data) IRIS_PP_REPEAT_2_I_26(macro, data) macro(26, data)
#define IRIS_PP_REPEAT_2_I_28(macro, data) IRIS_PP_REPEAT_2_I_27(macro, data) macro(27, data)
#define IRIS_PP_REPEAT_2_I_29(macro, data) IRIS_PP_REPEAT_2_I_28(macro, data) macro(28, data)
#define IRIS_PP_REPEAT_2_I_30(macro, data) IRIS_PP_REPEAT_2_I_29(macro, data) macro(29, data)
#define IRIS_PP_REPEAT_2_I_31(macro, data) IRIS_PP_REPEAT_2_I_30(macro, data) macro(30, data)
#define IRIS_PP_REPEAT_2_I_32(macro, data) IRIS_PP_REPEAT_2_I_31(macro, data) macro(31, data)

#define IRIS_PP_REPEAT_3_I_0(macro, data)
#define IRIS_PP_REPEAT_3_I_1(macro, data) macro(0, data)
#define IRIS_PP_REPEAT_3_I_2(macro, data) IRIS_PP_REPEAT_3_I_1(macro, data) macro(1, data)
#define IRIS_PP_REPEAT_3_I_3(macro, data) IRIS_PP_REPEAT_3_I_2(macro, data) macro(2, data)
#define IRIS_PP_REPEAT_3_I_4(macro, data) IRIS_PP_REPEAT_3_I_3(macro, data) macro(3, data)
#define IRIS_PP_REPEAT_3_I_5(macro, data) IRIS_PP_REPEAT_3_I_4(macro, data) macro(4, data)
#define IRIS_PP_REPEAT_3_I_6(macro, data) IRIS_PP_REPEAT_3_I_5(macro, data) macro(5, data)
#define IRIS_PP_REPEAT_3_I_7(macro, data) IRIS_PP_REPEAT_3_I_6(macro, data) macro(6, data)
#define IRIS_PP_REPEAT_3_I_8(macro, data) IRIS_PP_REPEAT_3_I_7(macro, data) macro(7, data)
#define IRIS_PP_REPEAT_3_I_9(macro, data) IRIS_PP_REPEAT_3_I_8(macro, data) macro(8, data)
#define IRIS_PP_REPEAT_3_I_10(macro, data) IRIS_PP_REPEAT_3_I_9(macro, data) macro(9, data)
#define IRIS_PP_REPEAT_3_I_11(macro, data) IRIS_PP_REPEAT_3_I_10(macro, data) macro(10, data)
#define IRIS_PP_REPEAT_3_I_12(macro, data) IRIS_PP_REPEAT_3_I_11(macro, data) macro(11, data)
#define IRIS_PP_REPEAT_3_I_13(macro, data) IRIS_PP_REPEAT_3_I_12(macro, data) macro(12, data)
#define IRIS_PP_REPEAT_3_I_14(macro, data) IRIS_PP_REPEAT_3_I_13(macro, data) macro(13, data)
#define IRIS_PP_REPEAT_3_I_15(macro, data) IRIS_PP_REPEAT_3_I_14(macro, data) macro(14, data)
#define IRIS_PP_REPEAT_3_I_16(macro, data) IRIS_PP_REPEAT_3_I_15(macro, data) macro(15, data)
#define IRIS_PP_REPEAT_3_I_17(macro, data) IRIS_PP_REPEAT_3_I_16(macro, data) macro(16, data)
#define IRIS_PP_REPEAT_3_I_18(macro, data) IRIS_PP_REPEAT_3_I_17(macro, data) macro(17, data)
#define IRIS_PP_REPEAT_3_I_19(macro, data) IRIS_PP_REPEAT_3_I_18(macro, data) macro(18, data)
#define IRIS_PP_REPEAT_3_I_20(macro, data) IRIS_PP_REPEAT_3_I_19(macro, data) macro(19, data)
#define IRIS_PP_REPEAT_3_I_21(macro, data) IRIS_PP_REPEAT_3_I_20(macro, data) macro(20, data)
#define IRIS_PP_REPEAT_3_I_22(macro, data) IRIS_PP_REPEAT_3_I_21(macro, data) macro(21, data)
#define IRIS_PP_REPEAT_3_I_23(macro, data) IRIS_PP_REPEAT_3_I_22(macro, data) macro(22, data)
#define IRIS_PP_REPEAT_3_I_24(macro, data) IRIS_PP_REPEAT_3_I_23(macro, data) macro(23, data)
#define IRIS_PP_REPEAT_3_I_25(macro, data) IRIS_PP_REPEAT_3_I_24(macro, data) macro(24, data)
#define IRIS_PP_REPEAT_3_I_26(macro, data) IRIS_PP_REPEAT_3_I_25(macro, data) macro(25, data)
#define IRIS_PP_REPEAT_3_I_27(macro, data) IRIS_PP_REPEAT_3_I_26(macro, data) macro(26, data)
#define IRIS_PP_REPEAT_3_I_28(macro, data) IRIS_PP_REPEAT_3_I_27(macro, data) macro(27, data)
#define IRIS_PP_REPEAT_3_I_29(macro, data) IRIS_PP_REPEAT_3_I_28(macro, data) macro(28, data)
#define IRIS_PP_REPEAT_3_I_30(macro, data) IRIS_PP_REPEAT_3_I_29(macro, data) macro(29, data)
#define IRIS_PP_REPEAT_3_I_31(macro, data) IRIS_PP_REPEAT_3_I_30(macro, data) macro(30, data)
#define IRIS_PP_REPEAT_3_I_32(macro, data) IRIS_PP_REPEAT_3_I_31(macro, data) macro(31, data)

#define IRIS_PP_REPEAT_4_I_0(macro, data)
#define IRIS_PP_REPEAT_4_I_1(macro, data) macro(0, data)
#define IRIS_PP_REPEAT_4_I_2(macro, data) IRIS_PP_REPEAT_4_I_1(macro, data) macro(1, data)
#define IRIS_PP_REPEAT_4_I_3(macro, data) IRIS_PP_REPEAT_4_I_2(macro, data) macro(2, data)
#define IRIS_PP_REPEAT_4_I_4(macro, data) IRIS_PP_REPEAT_4_I_3(macro, data) macro(3, data)
#define IRIS_PP_REPEAT_4_I_5(macro, data) IRIS_PP_REPEAT_4_I_4(macro, data) macro(4, data)
#define IRIS_PP_REPEAT_4_I_6(macro, data) IRIS_PP_REPEAT_4_I_5(macro, data) macro(5, data)
#define IRIS_PP_REPEAT_4_I_7(macro, data) IRIS_PP_REPEAT_4_I_6(macro, data) macro(6, data)
#define IRIS_PP_REPEAT_4_I_8(macro, data) IRIS_PP_REPEAT_4_I_7(macro, data) macro(7, data)
#define IRIS_PP_REPEAT_4_I_9(macro, data) IRIS_PP_REPEAT_4_I_8(macro, data) macro(8, data)
#define IRIS_PP_REPEAT_4_I_10(macro, data) IRIS_PP_REPEAT_4_I_9(macro, data) macro(9, data)
#define IRIS_PP_REPEAT_4_I_11(macro, data) IRIS_PP_REPEAT_4_I_10(macro, data) macro(10, data)
#define IRIS_PP_REPEAT_4_I_12(macro, data) IRIS_PP_REPEAT_4_I_11(macro, data) macro(11, data)
#define IRIS_PP_REPEAT_4_I_13(macro, data) IRIS_PP_REPEAT_4_I_12(macro, data) macro(12, data)
#define IRIS_PP_REPEAT_4_I_14(macro, data) IRIS_PP_REPEAT_4_I_13(macro, data) macro(13, data)
#define IRIS_PP_REPEAT_4_I_15(macro, data) IRIS_PP_REPEAT_4_I_14(macro, data) macro(14, data)
#define IRIS_PP_REPEAT_4_I_16(macro, data) IRIS_PP_REPEAT_4_I_15(macro, data) macro(15, data)
#define IRIS_PP_REPEAT_4_I_17(macro, data) IRIS_PP_REPEAT_4_I_16(macro, data) macro(16, data)
#define IRIS_PP_REPEAT_4_I_18(macro, data) IRIS_PP_REPEAT_4_I_17(macro, data) macro(17, data)
#define IRIS_PP_REPEAT_4_I_19(macro, data) IRIS_PP_REPEAT_4_I_18(macro, data) macro(18, data)
#define IRIS_PP_REPEAT_4_I_20(macro, data) IRIS_PP_REPEAT_4_I_19(macro, data) macro(19, data)
#define IRIS_PP_REPEAT_4_I_21(macro, data) IRIS_PP_REPEAT_4_I_20(macro, data) macro(20, data)
#define IRIS_PP_REPEAT_4_I_22(macro, data) IRIS_PP_REPEAT_4_I_21(macro, data) macro(21, data)
#define IRIS_PP_REPEAT_4_I_23(macro, data) IRIS_PP_REPEAT_4_I_22(macro, data) macro(22, data)
#define IRIS_PP_REPEAT_4_I_24(macro, data) IRIS_PP_REPEAT_4_I_23(macro, data) macro(23, data)
#define IRIS_PP_REPEAT_4_I_25(macro, data) IRIS_PP_REPEAT_4_I_24(macro, data) macro(24, data)
#define IRIS_PP_REPEAT_4_I_26(macro, data) IRIS_PP_REPEAT_4_I_25(macro, data) macro(25, data)
#define IRIS_PP_REPEAT_4_I_27(macro, data) IRIS_PP_REPEAT_4_I_26(macro, data) macro(26, data)
#define IRIS_PP_REPEAT_4_I_28(macro, data) IRIS_PP_REPEAT_4_I_27(macro, data) macro(27, data)
#define IRIS_PP_REPEAT_4_I_29(macro, data) IRIS_PP_REPEAT_4_I_28(macro, data) macro(28, data)
#define IRIS_PP_REPEAT_4_I_30(macro, data) IRIS_PP_REPEAT_4_I_29(macro, data) macro(29, data)
#define IRIS_PP_REPEAT_4_I_31(macro, data) IRIS_PP_REPEAT_4_I_30(macro, data) macro(30, data)
#define IRIS_PP_REPEAT_4_I_32(macro, data) IRIS_PP_REPEAT_4_I_31(macro, data) macro(31, data)

#define IRIS_PP_REPEAT_5_I_0(macro, data)
#define IRIS_PP_REPEAT_5_I_1(macro, data) macro(0, data)
#define IRIS_PP_REPEAT_5_I_2(macro, data) IRIS_PP_REPEAT_5_I_1(macro, data) macro(1, data)
#define IRIS_PP_REPEAT_5_I_3(macro, data) IRIS_PP_REPEAT_5_I_2(macro, data) macro(2, data)
#define IRIS_PP_REPEAT_5_I_4(macro, data) IRIS_PP_REPEAT_5_I_3(macro, data) macro(3, data)
#define IRIS_PP_REPEAT_5_I_5(macro, data) IRIS_PP_REPEAT_5_I_4(macro, data) macro(4, data)
#define IRIS_PP_REPEAT_5_I_6(macro, data) IRIS_PP_REPEAT_5_I_5(macro, data) macro(5, data)
#define IRIS_PP_REPEAT_5_I_7(macro, data) IRIS_PP_REPEAT_5_I_6(macro, data) macro(6, data)
#define IRIS_PP_REPEAT_5_I_8(macro, data) IRIS_PP_REPEAT_5_I_7(macro, data) macro(7, data)
#define IRIS_PP_REPEAT_5_I_9(macro, data) IRIS_PP_REPEAT_5_I_8(macro, data) macro(8, data)
#define IRIS_PP_REPEAT_5_I_10(macro, data) IRIS_PP_REPEAT_5_I_9(macro, data) macro(9, data)
#define IRIS_PP_REPEAT_5_I_11(macro, data) IRIS_PP_REPEAT_5_I_10(macro, data) macro(10, data)
#define IRIS_PP_REPEAT_5_I_12(macro, data) IRIS_PP_REPEAT_5_I_11(macro, data) macro(11, data)
#define IRIS_PP_REPEAT_5_I_13(macro, data) IRIS_PP_REPEAT_5_I_12(macro, data) macro(12, data)
#define IRIS_PP_REPEAT_5_I_14(macro, data) IRIS_PP_REPEAT_5_I_13(macro, data) macro(13, data)
#define IRIS_PP_REPEAT_5_I_15(macro, data) IRIS_PP_REPEAT_5_I_14(macro, data) macro(14, data)
#define IRIS_PP_REPEAT_5_I_16(macro, data) IRIS_PP_REPEAT_5_I_15(macro, data) macro(15, data)
#define IRIS_PP_REPEAT_5_I_17(macro, data) IRIS_PP_REPEAT_5_I_16(macro, data) macro(16, data)
#define IRIS_PP_REPEAT_5_I_18(macro, data) IRIS_PP_REPEAT_5_I_17(macro, data) macro(17, data)
#define IRIS_PP_REPEAT_5_I_19(macro, data) IRIS_PP_REPEAT_5_I_18(macro, data) macro(18, data)
#define IRIS_PP_REPEAT_5_I_20(macro, data) IRIS_PP_REPEAT_5_I_19(macro, data) macro(19, data)
#define IRIS_PP_REPEAT_5_I_21(macro, data) IRIS_PP_REPEAT_5_I_20(macro, data) macro(20, data)
#define IRIS_PP_REPEAT_5_I_22(macro, data) IRIS_PP_REPEAT_5_I_21(macro, data) macro(21, data)
#define IRIS_PP_REPEAT_5_I_23(macro, data) IRIS_PP_REPEAT_5_I_22(macro, data) macro(22, data)
#define IRIS_PP_REPEAT_5_I_24(macro, data) IRIS_PP_REPEAT_5_I_23(macro, data) macro(23, data)
#define IRIS_PP_REPEAT_5_I_25(macro, data) IRIS_PP_REPEAT_5_I_24(macro, data) macro(24, data)
#define IRIS_PP_REPEAT_5_I_26(macro, data) IRIS_PP_REPEAT_5_I_25(macro, data) macro(25, data)
#define IRIS_PP_REPEAT_5_I_27(macro, data) IRIS_PP_REPEAT_5_I_26(macro, data) macro(26, data)
#define IRIS_PP_REPEAT_5_I_28(macro, data) IRIS_PP_REPEAT_5_I_27(macro, data) macro(27, data)
#define IRIS_PP_REPEAT_5_I_29(macro, data) IRIS_PP_REPEAT_5_I_28(macro, data) macro(28, data)
#define IRIS_PP_REPEAT_5_I_30(macro, data) IRIS_PP_REPEAT_5_I_29(macro, data) macro(29, data)
#define IRIS_PP_REPEAT_5_I_31(macro, data) IRIS_PP_REPEAT_5_I_30(macro, data) macro(30, data)
#define IRIS_PP_REPEAT_5_I_32(macro, data) IRIS_PP_REPEAT_5_I_31(macro, data) macro(31, data)

#define IRIS_PP_REPEAT_6_I_0(macro, data)
#define IRIS_PP_REPEAT_6_I_1(macro, data) macro(0, data)
#define IRIS_PP_REPEAT_6_I_2(macro, data) IRIS_PP_REPEAT_6_I_1(macro, data) macro(1, data)
#define IRIS_PP_REPEAT_6_I_3(macro, data) IRIS_PP_REPEAT_6_I_2(macro, data) macro(2, data)
#define IRIS_PP_REPEAT_6_I_4(macro, data) IRIS_PP_REPEAT_6_I_3(macro, data) macro(3, data)
#define IRIS_PP_REPEAT_6_I_5(macro, data) IRIS_PP_REPEAT_6_I_4(macro, data) macro(4, data)
#define IRIS_PP_REPEAT_6_I_6(macro, data) IRIS_PP_REPEAT_6_I_5(macro, data) macro(5, data)
#define IRIS_PP_REPEAT_6_I_7(macro, data) IRIS_PP_REPEAT_6_I_6(macro, data) macro(6, data)
#define IRIS_PP_REPEAT_6_I_8(macro, data) IRIS_PP_REPEAT_6_I_7(macro, data) macro(7, data)
#define IRIS_PP_REPEAT_6_I_9(macro, data) IRIS_PP_REPEAT_6_I_8(macro, data) macro(8, data)
#define IRIS_PP_REPEAT_6_I_10(macro, data) IRIS_PP_REPEAT_6_I_9(macro, data) macro(9, data)
#define IRIS_PP_REPEAT_6_I_11(macro, data) IRIS_PP_REPEAT_6_I_10(macro, data) macro(10, data)
#define IRIS_PP_REPEAT_6_I_12(macro, data) IRIS_PP_REPEAT_6_I_11(macro, data) macro(11, data)
#define IRIS_PP_REPEAT_6_I_13(macro, data) IRIS_PP_REPEAT_6_I_12(macro, data) macro(12, data)
#define IRIS_PP_REPEAT_6_I_14(macro, data) IRIS_PP_REPEAT_6_I_13(macro, data) macro(13, data)
#define IRIS_PP_REPEAT_6_I_15(macro, data) IRIS_PP_REPEAT_6_I_14(macro, data) macro(14, data)
#define IRIS_PP_REPEAT_6_I_16(macro, data) IRIS_PP_REPEAT_6_I_15(macro, data) macro(15, data)
#define IRIS_PP_REPEAT_6_I_17(macro, data) IRIS_PP_REPEAT_6_I_16(macro, data) macro(16, data)
#define IRIS_PP_REPEAT_6_I_18(macro, data) IRIS_PP_REPEAT_6_I_17(macro, data) macro(17, data)
#define IRIS_PP_REPEAT_6_I_19(macro, data) IRIS_PP_REPEAT_6_I_18(macro, data) macro(18, data)
#define IRIS_PP_REPEAT_6_I_20(macro, data) IRIS_PP_REPEAT_6_I_19(macro, data) macro(19, data)
#define IRIS_PP_REPEAT_6_I_21(macro, data) IRIS_PP_REPEAT_6_I_20(macro, data) macro(20, data)
#define IRIS_PP_REPEAT_6_I_22(macro, data) IRIS_PP_REPEAT_6_I_21(macro, data) macro(21, data)
#define IRIS_PP_REPEAT_6_I_23(macro, data) IRIS_PP_REPEAT_6_I_22(macro, data) macro(22, data)
#define IRIS_PP_REPEAT_6_I_24(macro, data) IRIS_PP_REPEAT_6_I_23(macro, data) macro(23, data)
#define IRIS_PP_REPEAT_6_I_25(macro, data) IRIS_PP_REPEAT_6_I_24(macro, data) macro(24, data)
#define IRIS_PP_REPEAT_6_I_26(macro, data) IRIS_PP_REPEAT_6_I_25(macro, data) macro(25, data)
#define IRIS_PP_REPEAT_6_I_27(macro, data) IRIS_PP_REPEAT_6_I_26(macro, data) macro(26, data)
#define IRIS_PP_REPEAT_6_I_28(macro, data) IRIS_PP_REPEAT_6_I_27(macro, data) macro(27, data)
#define IRIS_PP_REPEAT_6_I_29(macro, data) IRIS_PP_REPEAT_6_I_28(macro, data) macro(28, data)
#define IRIS_PP_REPEAT_6_I_30(macro, data) IRIS_PP_REPEAT_6_I_29(macro, data) macro(29, data)
#define IRIS_PP_REPEAT_6_I_31(macro, data) IRIS_PP_REPEAT_6_I_30(macro, data) macro(30, data)
#define IRIS_PP_REPEAT_6_I_32(macro, data) IRIS_PP_REPEAT_6_I_31(macro, data) macro(31, data)

#define IRIS_PP_REPEAT_7_I_0(macro, data)
#define IRIS_PP_REPEAT_7_I_1(macro, data) macro(0, data)
#define IRIS_PP_REPEAT_7_I_2(macro, data) IRIS_PP_REPEAT_7_I_1(macro, data) macro(1, data)
#define IRIS_PP_REPEAT_7_I_3(macro, data) IRIS_PP_REPEAT_7_I_2(macro, data) macro(2, data)
#define IRIS_PP_REPEAT_7_I_4(macro, data) IRIS_PP_REPEAT_7_I_3(macro, data) macro(3, data)
#define IRIS_PP_REPEAT_7_I_5(macro, data) IRIS_PP_REPEAT_7_I_4(macro, data) macro(4, data)
#define IRIS_PP_REPEAT_7_I_6(macro, data) IRIS_PP_REPEAT_7_I_5(macro, data) macro(5, data)
#define IRIS_PP_REPEAT_7_I_7(macro, data) IRIS_PP_REPEAT_7_I_6(macro, data) macro(6, data)
#define IRIS_PP_REPEAT_7_I_8(macro, data) IRIS_PP_REPEAT_7_I_7(macro, data) macro(7, data)
#define IRIS_PP_REPEAT_7_I_9(macro, data) IRIS_PP_REPEAT_7_I_8(macro, data) macro(8, data)
#define IRIS_PP_REPEAT_7_I_10(macro, data) IRIS_PP_REPEAT_7_I_9(macro, data) macro(9, data)
#define IRIS_PP_REPEAT_7_I_11(macro, data) IRIS_PP_REPEAT_7_I_10(macro, data) macro(10, data)
#define IRIS_PP_REPEAT_7_I_12(macro, data) IRIS_PP_REPEAT_7_I_11(macro, data) macro(11, data)
#define IRIS_PP_REPEAT_7_I_13(macro, data) IRIS_PP_REPEAT_7_I_12(macro, data) macro(12, data)
#define IRIS_PP_REPEAT_7_I_14(macro, data) IRIS_PP_REPEAT_7_I_13(macro, data) macro(13, data)
#define IRIS_PP_REPEAT_7_I_15(macro, data) IRIS_PP_REPEAT_7_I_14(macro, data) macro(14, data)
#define IRIS_PP_REPEAT_7_I_16(macro, data) IRIS_PP_REPEAT_7_I_15(macro, data) macro(15, data)
#define IRIS_PP_REPEAT_7_I_17(macro, data) IRIS_PP_REPEAT_7_I_16(macro, data) macro(16, data)
#define IRIS_PP_REPEAT_7_I_18(macro, data) IRIS_PP_REPEAT_7_I_17(macro, data) macro(17, data)
#define IRIS_PP_REPEAT_7_I_19(macro, data) IRIS_PP_REPEAT_7_I_18(macro, data) macro(18, data)
#define IRIS_PP_REPEAT_7_I_20(macro, data) IRIS_PP_REPEAT_7_I_19(macro, data) macro(19, data)
#define IRIS_PP_REPEAT_7_I_21(macro, data) IRIS_PP_REPEAT_7_I_20(macro, data) macro(20, data)
#define IRIS_PP_REPEAT_7_I_22(macro, data) IRIS_PP_REPEAT_7_I_21(macro, data) macro(21, data)
#define IRIS_PP_REPEAT_7_I_23(macro, data) IRIS_PP_REPEAT_7_I_22(macro, data) macro(22, data)
#define IRIS_PP_REPEAT_7_I_24(macro, data) IRIS_PP_REPEAT_7_I_23(macro, data) macro(23, data)
#define IRIS_PP_REPEAT_7_I_25(macro, data) IRIS_PP_REPEAT_7_I_24(macro, data) macro(24, data)
#define IRIS_PP_REPEAT_7_I_26(macro, data) IRIS_PP_REPEAT_7_I_25(macro, data) macro(25, data)
#define IRIS_PP_REPEAT_7_I_27(macro, data) IRIS_PP_REPEAT_7_I_26(macro, data) macro(26, data)
#define IRIS_PP_REPEAT_7_I_28(macro, data) IRIS_PP_REPEAT_7_I_27(macro, data) macro(27, data)
#define IRIS_PP_REPEAT_7_I_29(macro, data) IRIS_PP_REPEAT_7_I_28(macro, data) macro(28, data)
#define IRIS_PP_REPEAT_7_I_30(macro, data) IRIS_PP_REPEAT_7_I_29(macro, data) macro(29, data)
#define IRIS_PP_REPEAT_7_I_31(macro, data) IRIS_PP_REPEAT_7_I_30(macro, data) macro(30, data)
#define IRIS_PP_REPEAT_7_I_32(macro, data) IRIS_PP_REPEAT_7_I_31(macro, data) macro(31, data)

#define IRIS_PP_REPEAT_8_I_0(macro, data)
#define IRIS_PP_REPEAT_8_I_1(macro, data) macro(0, data)
#define IRIS_PP_REPEAT_8_I_2(macro, data) IRIS_PP_REPEAT_8_I_1(macro, data) macro(1, data)
#define IRIS_PP_REPEAT_8_I_3(macro, data) IRIS_PP_REPEAT_8_I_2(macro, data) macro(2, data)
#define IRIS_PP_REPEAT_8_I_4(macro, data) IRIS_PP_REPEAT_8_I_3(macro, data) macro(3, data)
#define IRIS_PP_REPEAT_8_I_5(macro, data) IRIS_PP_REPEAT_8_I_4(macro, data) macro(4, data)
#define IRIS_PP_REPEAT_8_I_6(macro, data) IRIS_PP_REPEAT_8_I_5(macro, data) macro(5, data)
#define IRIS_PP_REPEAT_8_I_7(macro, data) IRIS_PP_REPEAT_8_I_6(macro, data) macro(6, data)
#define IRIS_PP_REPEAT_8_I_8(macro, data) IRIS_PP_REPEAT_8_I_7(macro, data) macro(7, data)
#define IRIS_PP_REPEAT_8_I_9(macro, data) IRIS_PP_REPEAT_8_I_8(macro, data) macro(8, data)
#define IRIS_PP_REPEAT_8_I_10(macro, data) IRIS_PP_REPEAT_8_I_9(macro, data) macro(9, data)
#define IRIS_PP_REPEAT_8_I_11(macro, data) IRIS_PP_REPEAT_8_I_10(macro, data) macro(10, data)
#define IRIS_PP_REPEAT_8_I_12(macro, data) IRIS_PP_REPEAT_8_I_11(macro, data) macro(11, data)
#define IRIS_PP_REPEAT_8_I_13(macro, data) IRIS_PP_REPEAT_8_I_12(macro, data) macro(12, data)
#define IRIS_PP_REPEAT_8_I_14(macro, data) IRIS_PP_REPEAT_8_I_13(macro, data) macro(13, data)
#define IRIS_PP_REPEAT_8_I_15(macro, data) IRIS_PP_REPEAT_8_I_14(macro, data) macro(14, data)
#define IRIS_PP_REPEAT_8_I_16(macro, data) IRIS_PP_REPEAT_8_I_15(macro, data) macro(15, data)
#define IRIS_PP_REPEAT_8_I_17(macro, data) IRIS_PP_REPEAT_8_I_16(macro, data) macro(16, data)
#define IRIS_PP_REPEAT_8_I_18(macro, data) IRIS_PP_REPEAT_8_I_17(macro, data) macro(17, data)
#define IRIS_PP_REPEAT_8_I_19(macro, data) IRIS_PP_REPEAT_8_I_18(macro, data) macro(18, data)
#define IRIS_PP_REPEAT_8_I_20(macro, data) IRIS_PP_REPEAT_8_I_19(macro, data) macro(19, data)
#define IRIS_PP_REPEAT_8_I_21(macro, data) IRIS_PP_REPEAT_8_I_20(macro, data) macro(20, data)
#define IRIS_PP_REPEAT_8_I_22(macro, data) IRIS_PP_REPEAT_8_I_21(macro, data) macro(21, data)
#define IRIS_PP_REPEAT_8_I_23(macro, data) IRIS_PP_REPEAT_8_I_22(macro, data) macro(22, data)
#define IRIS_PP_REPEAT_8_I_24(macro, data) IRIS_PP_REPEAT_8_I_23(macro, data) macro(23, data)
#define IRIS_PP_REPEAT_8_I_25(macro, data) IRIS_PP_REPEAT_8_I_24(macro, data) macro(24, data)
#define IRIS_PP_REPEAT_8_I_26(macro, data) IRIS_PP_REPEAT_8_I_25(macro, data) macro(25, data)
#define IRIS_PP_REPEAT_8_I_27(macro, data) IRIS_PP_REPEAT_8_I_26(macro, data) macro(26, data)
#define IRIS_PP_REPEAT_8_I_28(macro, data) IRIS_PP_REPEAT_8_I_27(macro, data) macro(27, data)
#define IRIS_PP_REPEAT_8_I_29(macro, data) IRIS_PP_REPEAT_8_I_28(macro, data) macro(28, data)
#define IRIS_PP_REPEAT_8_I_30(macro, data) IRIS_PP_REPEAT_8_I_29(macro, data) macro(29, data)
#define IRIS_PP_REPEAT_8_I_31(macro, data) IRIS_PP_REPEAT_8_I_30(macro, data) macro(30, data)
#define IRIS_PP_REPEAT_8_I_32(macro, data) IRIS_PP_REPEAT_8_I_31(macro, data) macro(31, data)

#endif
