#ifndef IRIS_PREPROCESS_STRINGIZE_HPP
#define IRIS_PREPROCESS_STRINGIZE_HPP

// SPDX-License-Identifier: MIT

#define IRIS_PP_STRINGIZE(...) IRIS_PP_STRINGIZE_I(__VA_ARGS__)
#define IRIS_PP_STRINGIZE_I(...) #__VA_ARGS__

#endif
