#ifndef IRIS_PREPROCESS_WHILE_HPP
#define IRIS_PREPROCESS_WHILE_HPP

// SPDX-License-Identifier: MIT

#include <iris/pp/if.hpp>

#define IRIS_PP_WHILE(state, pred, update) IRIS_PP_WHILE_I_0(state, pred, update)

#define IRIS_PP_WHILE_I_0(state, pred, op) IRIS_PP_WHILE_I_I_0(state, pred, op)
#define IRIS_PP_WHILE_I_1(state, pred, op) IRIS_PP_WHILE_I_I_1(state, pred, op)
#define IRIS_PP_WHILE_I_2(state, pred, op) IRIS_PP_WHILE_I_I_2(state, pred, op)
#define IRIS_PP_WHILE_I_3(state, pred, op) IRIS_PP_WHILE_I_I_3(state, pred, op)
#define IRIS_PP_WHILE_I_4(state, pred, op) IRIS_PP_WHILE_I_I_4(state, pred, op)
#define IRIS_PP_WHILE_I_5(state, pred, op) IRIS_PP_WHILE_I_I_5(state, pred, op)
#define IRIS_PP_WHILE_I_6(state, pred, op) IRIS_PP_WHILE_I_I_6(state, pred, op)
#define IRIS_PP_WHILE_I_7(state, pred, op) IRIS_PP_WHILE_I_I_7(state, pred, op)
#define IRIS_PP_WHILE_I_8(state, pred, op) IRIS_PP_WHILE_I_I_8(state, pred, op)
#define IRIS_PP_WHILE_I_9(state, pred, op) IRIS_PP_WHILE_I_I_9(state, pred, op)
#define IRIS_PP_WHILE_I_10(state, pred, op) IRIS_PP_WHILE_I_I_10(state, pred, op)
#define IRIS_PP_WHILE_I_11(state, pred, op) IRIS_PP_WHILE_I_I_11(state, pred, op)
#define IRIS_PP_WHILE_I_12(state, pred, op) IRIS_PP_WHILE_I_I_12(state, pred, op)
#define IRIS_PP_WHILE_I_13(state, pred, op) IRIS_PP_WHILE_I_I_13(state, pred, op)
#define IRIS_PP_WHILE_I_14(state, pred, op) IRIS_PP_WHILE_I_I_14(state, pred, op)
#define IRIS_PP_WHILE_I_15(state, pred, op) IRIS_PP_WHILE_I_I_15(state, pred, op)
#define IRIS_PP_WHILE_I_16(state, pred, op) IRIS_PP_WHILE_I_I_16(state, pred, op)
#define IRIS_PP_WHILE_I_17(state, pred, op) IRIS_PP_WHILE_I_I_17(state, pred, op)
#define IRIS_PP_WHILE_I_18(state, pred, op) IRIS_PP_WHILE_I_I_18(state, pred, op)
#define IRIS_PP_WHILE_I_19(state, pred, op) IRIS_PP_WHILE_I_I_19(state, pred, op)
#define IRIS_PP_WHILE_I_20(state, pred, op) IRIS_PP_WHILE_I_I_20(state, pred, op)
#define IRIS_PP_WHILE_I_21(state, pred, op) IRIS_PP_WHILE_I_I_21(state, pred, op)
#define IRIS_PP_WHILE_I_22(state, pred, op) IRIS_PP_WHILE_I_I_22(state, pred, op)
#define IRIS_PP_WHILE_I_23(state, pred, op) IRIS_PP_WHILE_I_I_23(state, pred, op)
#define IRIS_PP_WHILE_I_24(state, pred, op) IRIS_PP_WHILE_I_I_24(state, pred, op)
#define IRIS_PP_WHILE_I_25(state, pred, op) IRIS_PP_WHILE_I_I_25(state, pred, op)
#define IRIS_PP_WHILE_I_26(state, pred, op) IRIS_PP_WHILE_I_I_26(state, pred, op)
#define IRIS_PP_WHILE_I_27(state, pred, op) IRIS_PP_WHILE_I_I_27(state, pred, op)
#define IRIS_PP_WHILE_I_28(state, pred, op) IRIS_PP_WHILE_I_I_28(state, pred, op)
#define IRIS_PP_WHILE_I_29(state, pred, op) IRIS_PP_WHILE_I_I_29(state, pred, op)
#define IRIS_PP_WHILE_I_30(state, pred, op) IRIS_PP_WHILE_I_I_30(state, pred, op)
#define IRIS_PP_WHILE_I_31(state, pred, op) IRIS_PP_WHILE_I_I_31(state, pred, op)

#define IRIS_PP_WHILE_I_EAT_3(state, pred, op)

#define IRIS_PP_WHILE_I_I_0(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_1, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_1(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_2, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_2(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_3, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_3(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_4, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_4(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_5, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_5(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_6, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_6(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_7, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_7(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_8, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_8(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_9, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_9(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_10, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_10(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_11, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_11(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_12, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_12(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_13, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_13(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_14, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_14(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_15, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_15(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_16, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_16(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_17, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_17(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_18, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_18(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_19, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_19(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_20, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_20(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_21, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_21(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_22, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_22(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_23, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_23(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_24, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_24(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_25, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_25(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_26, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_26(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_27, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_27(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_28, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_28(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_29, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_29(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_30, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_30(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_31, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)
#define IRIS_PP_WHILE_I_I_31(state, pred, op) IRIS_PP_IF(pred(state), IRIS_PP_WHILE_I_32, state IRIS_PP_WHILE_I_EAT_3)(op(state), pred, op)

#endif
